<?xml version="1.0" encoding="UTF-8" ?>
<!-- 外部引入 -->
<!DOCTYPE students SYSTEM "student.dtd">

<!-- 内部引入 -->
<!--<!DOCTYPE students [-->
        <!---->
        <!--<!ELEMENT students (student+) >-->
        <!--<!ELEMENT student (name,age,sex) >-->
        <!--<!ELEMENT name (#PCDATA) >-->
        <!--<!ELEMENT age (#PCDATA) >-->
        <!--<!ELEMENT sex (#PCDATA) >-->
        <!--<!ATTLIST student number ID #REQUIRED>-->
        <!---->
        <!--]>-->

<!--打个尖括号会有提示-->
<students>
    <student number="s001">
        <name>zhangsan</name>
        <age>23</age>
        <sex>male</sex>
    </student>
    <student number="s002">
        <name>lisi</name>
        <age>24</age>
        <sex>female</sex>
    </student>
</students>